### PR TITLE
Clear modules recursively

### LINKED ISSUE #6: Doesn't work for mongoose
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/clear-module/issues/6)

For other libraries it's OK but I have problems with clearing mongoose.

OS: Mac OS X 10.12.6
Node.js: 10.13.0
clear-module: 3.0.0
mongoose: 5.3.13

```js
const mongoose = require('mongoose');
const clearModule = require('clear-module');

clearModule('mongoose');
console.log(require('mongoose') === mongoose); // I expect false but it's true
```

> There is a $40.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/clear-module/issues/6).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/clear-module/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by omrilotan**
Motivation: One-stop-shop cleanup. For example - after finishing module tests with overridden dependencies:

```js
const clear = require('clear-module');

describe('test with mocking of dependencies', () => {
	let myModule;
	before(() => {
		// override some dependencies with mocks
		myModule = require('.');
	});
	after(() => clear('.', true)); // Forget about your worries
});
```

Fixes #6

### CODE REVIEW

**Comment by sindresorhus** [comment]
I wonder if this should just be the default behavior?

File: index.js [hunk 1]
```diff
@@ -39,4 +44,6 @@ clear.match = regex => {
 	}
 };
 
+clear.recursive = moduleId => clear(moduleId, true);
```
Comment (sindresorhus) [inline index.js]: I don't really see the point of having a separate method in addition to the argument on the default export.

Comment (omrilotan) [reply index.js]: I agree. Just wanted to allow a clean call option. Can be removed

**Comment by omrilotan** [comment]
Something about node 6 cache implementation keeps the instance of 'children' property. I can't get around all the 'parents' and 'children' references in node 6. 😭

**Comment by sindresorhus** [comment]
> I can't get around all the 'parents' and 'children' references in node 6. 😭

That's fine. I'm happy to target Node.js 8 and later.

**Comment by Attrash-Islam** [comment]
What happens if there's two modules (A and B) that depends on C module and I want to clear A module recursively. Does this affect B module badly?

**Comment by omrilotan** [comment]
@Attrash-Islam it does not remove references from inside computed closures. Everything should continue to work the same

**Comment by omrilotan** [comment]
@sindresorhus would you like me to modify this to be the default behaviour? (Should probably require a major version)

**Comment by sindresorhus** [comment]
> would you like me to modify this to be the default behaviour? (Should probably require a major version)

Yes

**Comment by sindresorhus** [comment]
I don't think we even need a `recursive` option. I cannot think of when you wouldn't want it.

**Comment by omrilotan** [comment]
I can change the logic of clear.all so we don't need it internally

**Comment by sindresorhus** [comment]
👍

**Comment by omrilotan** [comment]
Done.
`clear.all` is now a simple cleanup since it iterates over the entire cache (no recursiveness required)

**Comment by omrilotan** [comment]
Also eliminates #6 
```js
const clearModule = require('clear-module');
const mongoose = require('mongoose');

delete require.cache['mongoose'];
require('mongoose') === mongoose; // true
clearModule('mongoose');
require('mongoose') === mongoose; // false
```
